# Generated by Django 3.1.3 on 2021-11-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MR',
            fields=[
                ('anonymized_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('modality', models.CharField(max_length=3)),
                ('manufacturer', models.CharField(max_length=20)),
            ],
        ),
    ]
