# Generated by Django 3.1.3 on 2021-11-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MG',
            fields=[
                ('anonymized_id', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.SmallIntegerField()),
                ('modality', models.CharField(max_length=3)),
                ('manufacturer', models.CharField(max_length=200)),
                ('manufacturerModelName', models.CharField(max_length=200)),
                ('non_pCR_0_pCR_1', models.SmallIntegerField()),
                ('left_0_right_1', models.SmallIntegerField()),
                ('ER', models.SmallIntegerField()),
                ('PR', models.SmallIntegerField()),
                ('HER2', models.SmallIntegerField()),
                ('non_IDC_0_IDC_1', models.SmallIntegerField()),
                ('compressionForce', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MR',
            fields=[
                ('anonymized_id', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.SmallIntegerField()),
                ('modality', models.CharField(max_length=3)),
                ('manufacturer', models.CharField(max_length=200)),
                ('manufacturerModelName', models.CharField(max_length=200)),
                ('non_pCR_0_pCR_1', models.SmallIntegerField()),
                ('left_0_right_1', models.SmallIntegerField()),
                ('ER', models.SmallIntegerField()),
                ('PR', models.SmallIntegerField()),
                ('HER2', models.SmallIntegerField()),
                ('non_IDC_0_IDC_1', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='US',
            fields=[
                ('anonymized_id', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.SmallIntegerField()),
                ('modality', models.CharField(max_length=3)),
                ('manufacturer', models.CharField(max_length=200)),
                ('manufacturerModelName', models.CharField(max_length=200)),
                ('benign_0_malignant_1', models.SmallIntegerField()),
            ],
        ),
    ]
