# Generated by Django 3.1.3 on 2021-11-03 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DicomServiceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MG',
            fields=[
                ('mr_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DicomServiceApp.mr')),
                ('compressionForce', models.IntegerField()),
            ],
            bases=('DicomServiceApp.mr',),
        ),
    ]
